### ISSUE TITLE
PANIC: thread 'main' panicked at 'couldn't initialize the app

### ISSUE THREAD

**Issue by youngqqcn** [blockscout/blockscout-rs#129]
```
dir: No such file or directory (os error 2)
thread 'main' panicked at 'couldn't initialize the app: fetching list json returned error: error sending request for url (https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.list.json): error trying to connect: unexpected EOF', /data/blockscout-rs/smart-contract-verifier-http/src/run.rs:21:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by youngqqcn** [comment]
```
server::worker: Shutting down idle worker
2022-10-17T06:41:58.819884Z  INFO actix_server::worker: Shutting down idle worker
2022-10-17T06:41:58.819895Z  INFO actix_server::worker: Shutting down idle worker
2022-10-17T06:41:58.819902Z  INFO actix_server::accept: Accept thread stopped
2022-10-17T06:42:17.806999Z  INFO smart_contract_verifier_http::run: Smart-contract verifier is starting at 0.0.0.0:8043
2022-10-17T06:42:18.061065Z  INFO smart_contract_verifier::compiler::versions_fetcher: spawn version refresh job
2022-10-17T06:42:18.061161Z  INFO smart_contract_verifier::compiler::download_cache: found local compiler version v0.8.13+commit.abaa5c0e
thread 'main' panicked at 'couldn't initialize the app: fetching list json returned error: error sending request for url (https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.list.json): error trying to connect: unexpected EOF', /data/blockscout-rs/smart-contract-verifier-http/src/run.rs:21:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: tokio::park::thread::CachedParkThread::block_on
   5: tokio::runtime::Runtime::block_on
   6: smart_contract_verifier_http::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bragov4ik** [comment]
Is it still relevant?
